- hosts: openshift
  tasks:
    - name: Copy utils dependancy
      copy:
        src: ./utils.sh
        dest: ./utils.sh
        
    - name: Copy set env vars dependancy
      copy:
        src: ./set_env_vars.sh
        dest: ./set_env_vars.sh
  
    - name: Set environment vars and deploy
      script: ./6_deploy_test_app.sh
      environment:
        OPENSHIFT_USERNAME: "{{ lookup('retrieve_conjur_variable', 'openshift/username') }}"
        OPENSHIFT_PASSWORD: "{{ lookup('retrieve_conjur_variable', 'openshift/password') }}"      
